# Generated by Django 3.1.3 on 2020-11-15 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200430_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 12, 22, 38, 717924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Coat', 'Coat'), ('Pant', 'Pant'), ('Inner-Coat', 'Inner-Coat'), ('Shirt', 'Shirt'), ('Tie', 'Tie'), ('Daura-Suruwal', 'Daura-Surwal'), ('Dhaka-Topi', 'Dhaka-Topi')], max_length=50),
        ),
    ]
