# Generated by Django 3.1.3 on 2020-11-15 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20201115_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 13, 48, 9, 292123, tzinfo=utc)),
        ),
    ]
