# Generated by Django 3.1.3 on 2020-11-15 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20201115_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 13, 55, 34, 533427, tzinfo=utc)),
        ),
    ]
