# Generated by Django 3.1.3 on 2020-11-15 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20201115_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 14, 0, 24, 862989, tzinfo=utc)),
        ),
    ]
