# Generated by Django 3.1.3 on 2020-11-15 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20201115_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 14, 6, 37, 319999, tzinfo=utc)),
        ),
    ]
