# Generated by Django 3.1.2 on 2021-01-01 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20210101_0831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 3, 31, 3, 198043, tzinfo=utc)),
        ),
    ]
