# Generated by Django 3.1.2 on 2021-01-30 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20210101_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 12, 30, 0, 557667, tzinfo=utc)),
        ),
    ]
