# Generated by Django 3.1.6 on 2021-04-06 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20210406_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='trendingSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 3, 41, 57, 720966, tzinfo=utc)),
        ),
    ]
