# Generated by Django 3.1.6 on 2021-04-06 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20210406_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='price',
        ),
        migrations.AddField(
            model_name='trending',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 6, 55, 24, 522876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 6, 55, 24, 522876, tzinfo=utc)),
        ),
    ]
