# Generated by Django 3.1.6 on 2021-04-06 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20210406_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Name', models.CharField(max_length=100)),
                ('Sub_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 17, 12, 49, 61614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 17, 12, 49, 64613, tzinfo=utc)),
        ),
    ]
