# Generated by Django 3.1.2 on 2021-04-09 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_auto_20210406_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 15, 32, 20, 841871, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 15, 32, 20, 844870, tzinfo=utc)),
        ),
    ]
