# Generated by Django 3.1.2 on 2021-04-09 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_auto_20210409_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='site_Name',
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 15, 52, 49, 955081, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='trending',
        ),
    ]
