# Generated by Django 3.1.4 on 2021-04-11 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_auto_20210411_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitename',
            old_name='SubTitle',
            new_name='subTitle',
        ),
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 16, 13, 30, 961530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 16, 13, 30, 965527, tzinfo=utc)),
        ),
    ]
