# Generated by Django 3.1.4 on 2021-04-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_auto_20210412_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='mail',
            field=models.CharField(max_length=30),
        ),
    ]
