# Generated by Django 3.1.4 on 2021-04-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_auto_20210412_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
