# Generated by Django 3.1.4 on 2021-04-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0038_auto_20210412_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='siteName',
        ),
    ]
