# Generated by Django 3.1.4 on 2021-04-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0040_sitedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='siteDetails',
            new_name='siteDetail',
        ),
    ]
