# Generated by Django 3.1.4 on 2021-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_auto_20210416_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Coat', 'Coat'), ('Pant', 'Pant'), ('Inner-Coat', 'Inner-Coat'), ('Shirt', 'Shirt'), ('Tie', 'Tie'), ('Daura-Suruwal', 'Daura-Surwal'), ('Dhaka-Topi', 'Dhaka-Topi'), ('Sari', 'Sari'), ('Kurtha', 'Kurtha'), ('Lhenga', 'Lhenga'), ('Ladies-Jeans', 'Ladies-Jeans'), ('Ladies-Shirt', 'Ladies-Shirt'), ('Baby-fork', 'Baby-fork'), ('Baby-pamper', 'Baby-pamper')], max_length=50),
        ),
    ]
