# Generated by Django 3.1.4 on 2021-04-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0042_auto_20210425_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='siteDetail',
        ),
    ]
